In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
model = load_model('churn_model.h5')

2026-08-12 01:46:44.914366: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2026-08-12 01:46:44.914631: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-08-12 01:46:44.914848: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786479404.915182 28718257 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1786479404.915662 28718257 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)

with open('onehot_encoder_geography.pkl', 'rb') as f:
    onehot_encoder_geography = pickle.load(f)

In [29]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000.0,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000.0
}

In [30]:
geography_encoded = onehot_encoder_geography.transform([[input_data['Geography']]])
geography_encoded_df = pd.DataFrame(geography_encoded, columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
geography_encoded_df

/Users/shobhitjindal/ANN Classification Project/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [31]:
input_data_df = pd.DataFrame([input_data])
input_data_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1          50000.0

[1 rows x 10 columns]

In [32]:
input_data_df['Gender'] = label_encoder_gender.transform(input_data_df['Gender'])
input_data_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1          50000.0

[1 rows x 10 columns]

In [33]:
input_data_df = pd.concat([input_data_df.drop('Geography', axis = 1), geography_encoded_df], axis=1)
input_data_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [34]:
input_data_scaled = scaler.transform(input_data_df)
input_data_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [35]:
prediction = model.predict(input_data_scaled)
prediction

2026-08-12 02:01:20.055262: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 934ms/step

array([[0.00629116]], dtype=float32)

In [37]:
prediction_probability = prediction[0][0]
prediction_probability

np.float32(0.0062911627)

In [38]:
if prediction_probability > 0.5:
    prediction_result = 'Churn'
else:   
    prediction_result = 'Not Churn'

In [39]:
prediction_result

'Not Churn'