In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [3]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [4]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [5]:
onehot_encoder_geography = OneHotEncoder(sparse_output=False)
geography_encoded = onehot_encoder_geography.fit_transform(data[['Geography']])
geography_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
onehot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geography_encoded_df = pd.DataFrame(geography_encoded, columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
geography_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
data = pd.concat([data.drop('Geography', axis = 1), geography_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [9]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [12]:
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('onehot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geography, f)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model = Sequential([

    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])

model.summary()

/Users/shobhitjindal/ANN Classification Project/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-08-12 03:16:34.063531: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2026-08-12 03:16:34.063838: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-08-12 03:16:34.064184: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1786484794.064994 28848271 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1786484794.065637 28848271 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [17]:
log_dir = "regression_logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
history = model.fit(
    X_train_scaled, y_train, validation_data = (X_test_scaled, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

2026-08-12 03:19:22.519184: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 13393357824.0000 - mean_absolute_error: 100425.7578 - val_loss: 13043938304.0000 - val_mean_absolute_error: 98705.1172
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 13376713728.0000 - mean_absolute_error: 100343.5625 - val_loss: 13011400704.0000 - val_mean_absolute_error: 98540.6953
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 13324877824.0000 - mean_absolute_error: 100085.7969 - val_loss: 12943630336.0000 - val_mean_absolute_error: 98198.6797
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 13237918720.0000 - mean_absolute_error: 99654.4766 - val_loss: 12841257984.0000 - val_mean_absolute_error: 97683.6484
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 13114052608.0000 - mean_absolute_error: 99039.2188 - val_loss: 12701440000.0000 - val_mean_absolute_error: 96977.8594
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 12950151168.0000 - mean_absolute_error: 98226.2656 - val_loss: 12521451520.0000 - val_mean_absolute_error: 96064.4453
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 12744894464.0000 - mean_absolute_error: 97207.8750 - val_loss: 12299132928.0000 - val_mean_absolute_error: 94935.5781
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 12495760384.0000 - mean_absolute_error: 95972.8203 - val_loss: 12035479552.0000 - val_mean_absolute_error: 93599.1719
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 12204187648.0000 - mean_absolute_error: 94522.7734 - val_loss: 11728692224.0000 - val_mean_absolute_error: 92045.0781
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11870508032.0000 - mean_absolute_error: 92869.2422 - val_loss: 11380569088.0000 - val_mean_absolute_error: 90288.2578
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 11496147968.0000 - mean_absolute_error: 91012.7500 - val_loss: 10994913280.0000 - val_mean_absolute_error: 88326.3281
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 11085049856.0000 - mean_absolute_error: 88969.2656 - val_loss: 10574508032.0000 - val_mean_absolute_error: 86182.8594
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 10641088512.0000 - mean_absolute_error: 86762.9766 - val_loss: 10125662208.0000 - val_mean_absolute_error: 83921.3984
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 10170636288.0000 - mean_absolute_error: 84410.5938 - val_loss: 9650767872.0000 - val_mean_absolute_error: 81533.9531
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 9678586880.0000 - mean_absolute_error: 81953.8281 - val_loss: 9159179264.0000 - val_mean_absolute_error: 79046.4297
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 9167101952.0000 - mean_absolute_error: 79393.6562 - val_loss: 8654566400.0000 - val_mean_absolute_error: 76487.1328
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 8645321728.0000 - mean_absolute_error: 76762.6250 - val_loss: 8139479552.0000 - val_mean_absolute_error: 73864.6719
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 8117875712.0000 - mean_absolute_error: 74122.7812 - val_loss: 7626843136.0000 - val_mean_absolute_error: 71279.6250
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7592998912.0000 - mean_absolute_error: 71467.9141 - val_loss: 7118977536.0000 - val_mean_absolute_error: 68717.5625
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 7075468800.0000 - mean_absolute_error: 68854.7578 - val_loss: 6622611968.0000 - val_mean_absolute_error: 66235.8906
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 6575885824.0000 - mean_absolute_error: 66305.7812 - val_loss: 6147423232.0000 - val_mean_absolute_error: 63844.8789
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 6094658560.0000 - mean_absolute_error: 63849.1641 - val_loss: 5697181184.0000 - val_mean_absolute_error: 61566.1992
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 5643363840.0000 - mean_absolute_error: 61543.8984 - val_loss: 5275713024.0000 - val_mean_absolute_error: 59432.6562
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 5226720768.0000 - mean_absolute_error: 59407.2656 - val_loss: 4897905664.0000 - val_mean_absolute_error: 57544.9062
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 4850747392.0000 - mean_absolute_error: 57508.6641 - val_loss: 4555678208.0000 - val_mean_absolute_error: 55822.6758
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 4515154944.0000 - mean_absolute_error: 55786.3281 - val_loss: 4265536512.0000 - val_mean_absolute_error: 54377.0156
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 4229137920.0000 - mean_absolute_error: 54314.0547 - val_loss: 4013268480.0000 - val_mean_absolute_error: 53108.2383
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3988429568.0000 - mean_absolute_error: 53098.6641 - val_loss: 3810921472.0000 - val_mean_absolute_error: 52109.3438
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3791779328.0000 - mean_absolute_error: 52080.8945 - val_loss: 3651104000.0000 - val_mean_absolute_error: 51353.5312
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3639548672.0000 - mean_absolute_error: 51285.9414 - val_loss: 3533237248.0000 - val_mean_absolute_error: 50809.2422
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3525662720.0000 - mean_absolute_error: 50693.4961 - val_loss: 3446380032.0000 - val_mean_absolute_error: 50408.8984
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3444218624.0000 - mean_absolute_error: 50268.4844 - val_loss: 3389650432.0000 - val_mean_absolute_error: 50157.0391
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3387353344.0000 - mean_absolute_error: 49980.8750 - val_loss: 3353908736.0000 - val_mean_absolute_error: 50007.8594
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3352352000.0000 - mean_absolute_error: 49809.8320 - val_loss: 3332795904.0000 - val_mean_absolute_error: 49925.3008
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3330471424.0000 - mean_absolute_error: 49702.2891 - val_loss: 3321366272.0000 - val_mean_absolute_error: 49893.7734
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3318219264.0000 - mean_absolute_error: 49649.2734 - val_loss: 3320355072.0000 - val_mean_absolute_error: 49876.5312
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 3312717056.0000 - mean_absolute_error: 49623.3594 - val_loss: 3314354176.0000 - val_mean_absolute_error: 49870.6953
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3308731136.0000 - mean_absolute_error: 49604.2070 - val_loss: 3314125824.0000 - val_mean_absolute_error: 49870.5508
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3307067904.0000 - mean_absolute_error: 49599.2031 - val_loss: 3314673408.0000 - val_mean_absolute_error: 49875.4609
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 3306238976.0000 - mean_absolute_error: 49593.9141 - val_loss: 3316488192.0000 - val_mean_absolute_error: 49877.1016
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3306317056.0000 - mean_absolute_error: 49590.4336 - val_loss: 3315015680.0000 - val_mean_absolute_error: 49886.5234
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3305986304.0000 - mean_absolute_error: 49594.1680 - val_loss: 3314789376.0000 - val_mean_absolute_error: 49883.6680
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3305164288.0000 - mean_absolute_error: 49589.9688 - val_loss: 3314615552.0000 - val_mean_absolute_error: 49880.1602
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3306019584.0000 - mean_absolute_error: 49599.7773 - val_loss: 3315450880.0000 - val_mean_absolute_error: 49874.2148
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3305267712.0000 - mean_absolute_error: 49597.5469 - val_loss: 3317542656.0000 - val_mean_absolute_error: 49874.0469
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 3305645568.0000 - mean_absolute_error: 49605.5000 - val_loss: 3315414528.0000 - val_mean_absolute_error: 49868.9023
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3303839232.0000 - mean_absolute_error: 49574.4961 - val_loss: 3318904320.0000 - val_mean_absolute_error: 49921.8945
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 3304832000.0000 - mean_absolute_error: 49596.2266 - val_loss: 3314515200.0000 - val_mean_absolute_error: 49869.8320

In [20]:
%load_ext tensorboard

In [21]:
%tensorboard --logdir regression_logs/

In [22]:
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3314125824.0000 - mean_absolute_error: 49870.5508
Test Loss: 3314125824.0, Test MAE: 49870.55078125

In [23]:
model.save('regression_churn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.